version: "3"
services:
  web:
    env_file:
      - .docker.env
    image: qhyun2/watch-mega:latest
    ports:
      - "80:3000"
    volumes:
      - /home/howard/data:/app/data
    restart: always
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - /home/howard/data:/data
