version: "3"
services:
  web:
    env_file:
      - .docker.env
    links:
      - redis
    image: qhyun2/watch-mega:latest
    ports:
      - "80:3000"
    volumes:
      - /home/howard/videos:/app/public/videos
      - /home/howard/subs:/app/public/subs
    restart: always
  redis:
    image: redis:6.0
