name: CI

on:
  push:
    branches:
      - "master"

jobs:
  docker-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push SocketIO backend
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.server
          push: true
          tags: ghcr.io/qhyun2/watchmega:latest-server

      - name: Build and push next container
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.next
          push: true
          tags: ghcr.io/qhyun2/watchmega:latest-next
